---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Search for SAPEXE file
  find:
    paths: "{{ ascs_complete_kernel_install_folder }}/"
    patterns: 'SAPEXE_*SAR'
  register: sapexe_found
  failed_when: sapexe_found.matched != 1

- name: Store SAPEXE file full path
  set_fact: SAP_EXE_PATH="{{ sapexe_found.files[0].path }}"

- name: Store SAPHOSTAGENT file full path
  set_fact: SAP_HOSTAGENT_PATH="{{ ascs_complete_kernel_install_folder }}"

- name: Ensure installation folder exists
  file:
    path: "{{ folder_to_run_installation_from }}"
    state: directory
    mode: 0777

- name: Create params file for ASCS installation
  template:
    src: ascs.params
    dest: "{{ params_file_full_path }}"
    mode: 0777