---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Ensure group "{{ sapinst_user_group_name }}" exists
  group:
    name: "{{ sapinst_user_group_name }}"
    state: present

- name: Add current user to "{{ sapinst_user_group_name }}" group
  user:
    name: "{{ ansible_user_id }}"
    group: "{{ sapinst_user_group_name }}"

- name: Ensure installation folder exists
  file:
    path: "{{ folder_to_run_installation_from }}"
    state: directory
    group: "{{ sapinst_user_group_name }}"
    mode: 0777

- name: Build command
  set_fact: install_command="{{ ascs_complete_swpm_sum_install_folder }}/sapinst SAPINST_INPUT_PARAMETERS_URL={{ params_file_full_path }} SAPINST_EXECUTE_PRODUCT_ID={{ product_id_to_install }} SAPINST_USE_HOSTNAME={{ GLOBAL_INPUT_HOSTNAME }} SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false"

- name: Install ASCS
  shell: 
    cmd: "{{ install_command }}"
    chdir: "{{ folder_to_run_installation_from }}"
  no_log: yes
  register: installation_output
  ignore_errors: yes
  throttle: 1

- name: Show errors if they exist
  debug:
    msg: "{{ installation_output.stdout_lines }}"
  when: installation_output is defined and installation_output.rc != 0

- name: Abort execution when there are installation errors
  fail:
    msg: "Execution interrupted due to errors"
  when: installation_output is defined and installation_output.rc != 0