---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Install ZYPPER dependencies
  zypper:
    name: "{{ suse_packages }}"
    state: present
  register: log_output