---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Required variables caught from the user
GLOBAL_INPUT_HOSTNAME: "{{ EC2_HOSTNAME }}"
GLOBAL_INPUT_DNS_ZONE: "{{ PRIVATE_DNS_ZONE }}"
GLOBAL_MASTER_PASSWORD: "{{ MASTER_PASSWORD }}"
GLOBAL_ASCS_SID: "{{ ASCS_SID }}"
GLOBAL_EFS_ID: "{{ EFS_ID }}"
GLOBAL_ASCS_INSTANCE_NUMBER: "{{ ASCS_INSTANCE_NUMBER }}"

GLOBAL_ASCS_PRODUCT_ID: "{{ ASCS_PRODUCT_ID }}"

# Removes trailing slashes
GLOBAL_S3_DOWNLOAD_BUCKET_URL: "{{ S3_BUCKET_MEDIA_FILES | regex_replace('\\/$', '') }}"
GLOBAL_HANA_PRIVATE_IP: "{{ HANA_PRIVATE_IP }}"
GLOBAL_HANA_HOSTNAME: "{{ HANA_HOSTNAME }}"

# Optional variables caught from the user
GLOBAL_PAS_PRIVATE_IP: "{{ PAS_PRIVATE_IP }}"
GLOBAL_PAS_HOSTNAME: "{{ PAS_HOSTNAME }}"

# Optional HA variables
GLOBAL_ENABLE_HA: "{{ ENABLE_HA }}"
GLOBAL_PRIMARY_IP: "{{ HA_PRIMARY_PRIVATE_IP }}"
GLOBAL_NODE_IPS: "{{ HA_NODE_PRIVATE_IPS | regex_replace('\\,$', '') }}"
GLOBAL_NODE_IPS_LIST: ""

GLOBAL_LOGS_AND_FOLDERS_ROLE_NAME: prepare-logs-folders

sap_domain: "{{ GLOBAL_INPUT_DNS_ZONE }}"